"""Typed contracts shared by n8n, Pydantic AI, and persistence code."""

from .blogging import (
    MIN_BLOG_WORD_COUNT,
    MIN_TARGET_WORD_RATIO,
    BlogAgentResult,
    BlogCategory,
    BlogDraft,
    BlogDraftMetadata,
    BlogJobEnvelope,
    BlogJobInput,
    BlogOutline,
    BlogRuntimeContext,
    BlogSectionDraft,
    BlogValidationReport,
    Citation,
    OutlineSection,
    SEOData,
    SourceReference,
    ValidationIssue,
    count_blog_words,
    minimum_blog_word_count,
)

__all__ = [
    "MIN_BLOG_WORD_COUNT",
    "MIN_TARGET_WORD_RATIO",
    "BlogAgentResult",
    "BlogCategory",
    "BlogDraft",
    "BlogDraftMetadata",
    "BlogJobEnvelope",
    "BlogJobInput",
    "BlogOutline",
    "BlogRuntimeContext",
    "BlogSectionDraft",
    "BlogValidationReport",
    "Citation",
    "OutlineSection",
    "SEOData",
    "SourceReference",
    "ValidationIssue",
    "count_blog_words",
    "minimum_blog_word_count",
]
